---
title: "April 2022: 30 Day Chart Challenge"
author:
  - name: Clark Sims 
date: "`r Sys.Date()`"
output: 
  distill::distill_article
    toc: true
    toc_float: true

knit: crsp::knit_html_to_outputs
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  fig.retina = 3,
  fig.path = here::here("exports", "April_2022", "/")
)

pacman::p_load(janitor, pacman, rio, skimr, here, conflicted,
               tidyverse, crsp, gt)

conflict_prefer("clean_names", "janitor")
conflict_prefer("filter", "dplyr")

theme_set(theme_bw(base_size = 15) + theme(legend.position = "bottom"))
```

# **Introduction**

For April I am going to complete some of the [30 Day Chart Challenge](https://github.com/dominicroye/30DayChartChallenge_Edition2022).


# Day 1: Part-to-Whole

```{r d1-setup, include = FALSE}
tx_sum <- txhousing %>% 
  group_by(year) %>% 
  mutate(total_sales = sum(sales, na.rm = TRUE)) %>% 
  ungroup() %>% 
  group_by(year, month) %>% 
  mutate(monthly_sales = sum(sales, na.rm = TRUE)) %>% 
  ungroup() %>% 
  distinct(year, month, .keep_all = TRUE) %>% 
  select(year, month, total_sales, monthly_sales) %>% 
  rowwise() %>% 
  mutate(monthly_pct = (monthly_sales / total_sales) * 100) %>% 
  ungroup() %>% 
  mutate(hsize = 2) %>% 
  left_join(tibble(
    month = seq(1:12),
    month_name = month.abb
)) %>% 
  mutate(month_name = factor(month_name, levels = month.abb))


```

```{r d1-chart, include = TRUE}
# tx_sum %>% 
#   group_by(month) %>% 
#   summarize(mean_pct = mean(monthly_pct, na.rm = TRUE)) %>% 
#   mutate(ymax = cumsum(mean_pct),
#          ymin = dplyr::lag(mean_pct, default = 0)) %>% 
#   ggplot(aes(xmin = 3, xmax = 4, ymin = ymax, ymax = ymin, fill = as.factor(month))) + 
#   geom_rect() + 
#   coord_polar(theta = "y") + 
#   xlim(c(2, 4)) + 
#   facet_wrap(~ year)

tx_sum %>% 
  filter(year %in% c(2000, 2008, 2014)) %>%
  ggplot(aes(x = hsize, y = monthly_pct, fill = month_name)) + 
  geom_col(width = 0.2, position = "stack", color = "white", size = 0.25) + 
  coord_polar(theta = "y", direction = -1) +
  xlim(c(1.7, 2.3)) + 
  labs(fill = NULL) + 
  paletteer::scale_fill_paletteer_d("ggthemes::Red_Blue_Brown") +
  facet_wrap(~ year) + 
  theme_void() + 
  labs(title = "Percent of Houses Sold in Texas by Month") + 
  guides(fill = guide_legend(direction = "horizontal", nrow = 1)) + 
  theme(legend.position = "bottom", legend.direction = "horizontal", 
        strip.text = element_text(size = 16, family = "sanserif", color = "#565656"),
        legend.text = element_text(size = 12, color = "#565656"),
        aspect.ratio = 1, 
        plot.title = element_text(size = 24, hjust = 0.5, vjust = 1))



```

# Day 4: Flora

```{r d4-setup, include = FALSE}
p_load(rgbif)

sun <- name_suggest(q = 'Helianthus annuus', rank = 'species')$data$key[1]

sun_n <- as.numeric(occ_search(taxonKey = sun)$meta$count)

bes <- name_suggest(q = 'Rudbeckia hirta', rank = 'species')$data$key[1]

bes_n <- as.numeric(occ_search(taxonKey = bes)$meta$count)

flora <- tibble(
  com_name = c("Sunflower", "Blackeyed Susan"),
  sci_name = c("Helianthus annuus", "Rudbeckia hirta"),
  occurences = c(sun_n, bes_n)
)
```

```{r d4-chart, include = TRUE}
flora %>% 
  ggplot(aes(com_name, occurences)) + 
  geom_point(shape = 8, size = 20, color = "yellow") +
  geom_point(size = 6, color = "black") + 
  scale_y_continuous(limits = c(0, 100000)) +
  theme(panel.background = element_rect(fill = "blue"))
```

```{r knit-exit, include = FALSE}
knitr::knit_exit()
```

template, {rprojroot}, {rgbif}, {geoviz}, {ggmap}, {rayvista}, {camcorder}, {rayvertex}, {pwr}, {reprex}, debug = T for geom_text, {lcmm}, {rolldown}, {muvr}, {pcalg}, {packagemetrics}, {steveproj}, {ungeviz}, {themis}, {prettydoc}, {annotate}, {printy}, {roughsf}, {colorspace}, {monochromeR}, {colorblindr} 


<https://github.com/richardvogg/30DayMapChallenge21>

<https://albert-rapp.de/post/2021-09-16-similar-data-and-list-like-columns/#helpful-concepts>

<https://www.swisstopo.admin.ch/>

<https://www.ign.es/web/ign/portal/cbg-area-cartografia>

<http://shadedrelief.com/SampleElevationModels/>

<https://www.neonscience.org/resources/learning-hub/tutorials>

<https://docs.ropensci.org/rgbif/articles/rgbif.html>

<https://ryo-n7.github.io/2020-05-14-webscrape-soccer-data-with-R/>

<https://github.com/gkaramanis/aRt/blob/master/split-bar/split-bar.R>

<https://github.com/thebioengineer/camcorder>

<https://gist.github.com/Worville/c4149ece45a75928a404d316151ba0fe>

<https://www.tjmahr.com/lists-knitr-secret-weapon/>