---
title: "May 2022"
format:
  html:
    theme: yeti
    
    toc: true
    toc-title: "Daily R"
    number-sections: true
    
    mainfont: "Fira Code"
    linkcolor: "#cc7000"
    
    code-fold: true
    code-overflow: "scroll"
    code-link: true
    code-copy: true
    
    execute:
      echo: false
      warning: false
      message: false
      freeze: auto
    
    fig-dpi: 300
    fig-format: "png"
    
    link-external-icon: true
    link-external-newwindow: true
    
---

Using Quarto again.

# Setup || 2022-05-02 and 2022-05-03

Today I played with some of the [setup options](https://quarto.org/docs/reference/formats/html.html)

```{r quarto-setup}
#| echo: false
#| include: false

pacman::p_load(tidyverse)
```


```{r ggplot-example}
#| echo: true
mpg %>% 
  ggplot(aes(as.factor(cyl), cty)) + 
  geom_boxplot(outlier.shape = NA) + 
  geom_jitter(alpha = 0.5, width = 0.15)
```

# {echarts4r} || 2022-05-04

```{r echarts4r-setup}
#| include: false

pacman::p_load(echarts4r)

df <- state.x77 |> 
  as.data.frame() |> 
  tibble::rownames_to_column("State")

df |> 
  e_charts(State) |> # initialise and set x
  e_line(Population, smooth = FALSE) |>  # add a line
  e_area(Income, smooth = FALSE) |>  # add area
  e_x_axis(name = "States") |>  # add x axis name
  e_title(text = "US States", subtext = "Population & Income") |>  # Add title & subtitle
  e_theme("infographic") |>  # theme
  e_legend(right = 1) |> # move legend to the bottom
  e_tooltip(
    axisPointer = list(
      type = "cross"
    )
  ) 

```



```{r end-knit, include = FALSE}
knitr::knit_exit()
```


# Extra Stuff

template, {rprojroot}, {rgbif}, {geoviz}, {ggmap}, {rayvista}, {camcorder}, {rayvertex}, {pwr}, {reprex}, {lcmm}, {rolldown}, {muvr}, {pcalg}, {packagemetrics}, {steveproj}, {ungeviz}, {themis}, {prettydoc}, {annotate}, {printy}, {roughsf}, {colorspace}, {monochromeR}, {colorblindr}, {echarts4r}, {ggtext}